@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\vijayyadav\Desktop\Untitled (3)\frontend\node_modules\.pnpm\@typescript+native-preview@7.0.0-dev.20260505.1\node_modules\@typescript\native-preview\node_modules;C:\Users\vijayyadav\Desktop\Untitled (3)\frontend\node_modules\.pnpm\@typescript+native-preview@7.0.0-dev.20260505.1\node_modules;C:\Users\vijayyadav\Desktop\Untitled (3)\frontend\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\vijayyadav\Desktop\Untitled (3)\frontend\node_modules\.pnpm\@typescript+native-preview@7.0.0-dev.20260505.1\node_modules\@typescript\native-preview\node_modules;C:\Users\vijayyadav\Desktop\Untitled (3)\frontend\node_modules\.pnpm\@typescript+native-preview@7.0.0-dev.20260505.1\node_modules;C:\Users\vijayyadav\Desktop\Untitled (3)\frontend\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\@typescript\native-preview\bin\tsgo.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\@typescript\native-preview\bin\tsgo.js" %*
)
